name: Node Github CI

on:
  push:
    branches:
      - main
env:
  SHUHENG: ${{ vars.SHUHENG  }}
  LI: meng
jobs:
  test:

    runs-on: ubuntu-latest
    environment: build

    strategy:
      matrix:
        node-version: [19.x]
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm run test
      env:
        CI: true
        TOKEN: ${{ secrets.TOKEN}}
