name: Node Github CI

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: echo "token is ${TOKEN}, token1 is ${TOKEN1}"
      env:
        CI: true
        TOKEN: ${{ vars.TOKEN }}